Define hyper-parameters and other size

In [4]:
N=30 # number of samples
K=3  # the number of classes
D=4  # size of dimension OR number of independent variables
H=10 # size of hidden layer

In [5]:
import numpy as np
np.random.seed(42)
# X is input samples
X=np.round(np.random.rand(N,D),2)
# R is the output
R=np.repeat([[1,0,0], [0,1,0], [0,0,1]],10, axis=0)

In [6]:
np.c_[X,R]

array([[0.37, 0.95, 0.73, 0.6 , 1.  , 0.  , 0.  ],
       [0.16, 0.16, 0.06, 0.87, 1.  , 0.  , 0.  ],
       [0.6 , 0.71, 0.02, 0.97, 1.  , 0.  , 0.  ],
       [0.83, 0.21, 0.18, 0.18, 1.  , 0.  , 0.  ],
       [0.3 , 0.52, 0.43, 0.29, 1.  , 0.  , 0.  ],
       [0.61, 0.14, 0.29, 0.37, 1.  , 0.  , 0.  ],
       [0.46, 0.79, 0.2 , 0.51, 1.  , 0.  , 0.  ],
       [0.59, 0.05, 0.61, 0.17, 1.  , 0.  , 0.  ],
       [0.07, 0.95, 0.97, 0.81, 1.  , 0.  , 0.  ],
       [0.3 , 0.1 , 0.68, 0.44, 1.  , 0.  , 0.  ],
       [0.12, 0.5 , 0.03, 0.91, 0.  , 1.  , 0.  ],
       [0.26, 0.66, 0.31, 0.52, 0.  , 1.  , 0.  ],
       [0.55, 0.18, 0.97, 0.78, 0.  , 1.  , 0.  ],
       [0.94, 0.89, 0.6 , 0.92, 0.  , 1.  , 0.  ],
       [0.09, 0.2 , 0.05, 0.33, 0.  , 1.  , 0.  ],
       [0.39, 0.27, 0.83, 0.36, 0.  , 1.  , 0.  ],
       [0.28, 0.54, 0.14, 0.8 , 0.  , 1.  , 0.  ],
       [0.07, 0.99, 0.77, 0.2 , 0.  , 1.  , 0.  ],
       [0.01, 0.82, 0.71, 0.73, 0.  , 1.  , 0.  ],
       [0.77, 0.07, 0.36, 0.12,

In [7]:
# Adding some pattern into X
X[:10,:]=X[:10,:]*2
X[10:20,:]=X[10:20,:]*5
X

array([[0.74, 1.9 , 1.46, 1.2 ],
       [0.32, 0.32, 0.12, 1.74],
       [1.2 , 1.42, 0.04, 1.94],
       [1.66, 0.42, 0.36, 0.36],
       [0.6 , 1.04, 0.86, 0.58],
       [1.22, 0.28, 0.58, 0.74],
       [0.92, 1.58, 0.4 , 1.02],
       [1.18, 0.1 , 1.22, 0.34],
       [0.14, 1.9 , 1.94, 1.62],
       [0.6 , 0.2 , 1.36, 0.88],
       [0.6 , 2.5 , 0.15, 4.55],
       [1.3 , 3.3 , 1.55, 2.6 ],
       [2.75, 0.9 , 4.85, 3.9 ],
       [4.7 , 4.45, 3.  , 4.6 ],
       [0.45, 1.  , 0.25, 1.65],
       [1.95, 1.35, 4.15, 1.8 ],
       [1.4 , 2.7 , 0.7 , 4.  ],
       [0.35, 4.95, 3.85, 1.  ],
       [0.05, 4.1 , 3.55, 3.65],
       [3.85, 0.35, 1.8 , 0.6 ],
       [0.86, 0.62, 0.33, 0.06],
       [0.31, 0.33, 0.73, 0.64],
       [0.89, 0.47, 0.12, 0.71],
       [0.76, 0.56, 0.77, 0.49],
       [0.52, 0.43, 0.03, 0.11],
       [0.03, 0.64, 0.31, 0.51],
       [0.91, 0.25, 0.41, 0.76],
       [0.23, 0.08, 0.29, 0.16],
       [0.93, 0.81, 0.63, 0.87],
       [0.8 , 0.19, 0.89, 0.54]])

In [9]:
#Adding Ones to the X as first bias input
X=np.c_[np.ones(30), X]
X

array([[1.  , 0.74, 1.9 , 1.46, 1.2 ],
       [1.  , 0.32, 0.32, 0.12, 1.74],
       [1.  , 1.2 , 1.42, 0.04, 1.94],
       [1.  , 1.66, 0.42, 0.36, 0.36],
       [1.  , 0.6 , 1.04, 0.86, 0.58],
       [1.  , 1.22, 0.28, 0.58, 0.74],
       [1.  , 0.92, 1.58, 0.4 , 1.02],
       [1.  , 1.18, 0.1 , 1.22, 0.34],
       [1.  , 0.14, 1.9 , 1.94, 1.62],
       [1.  , 0.6 , 0.2 , 1.36, 0.88],
       [1.  , 0.6 , 2.5 , 0.15, 4.55],
       [1.  , 1.3 , 3.3 , 1.55, 2.6 ],
       [1.  , 2.75, 0.9 , 4.85, 3.9 ],
       [1.  , 4.7 , 4.45, 3.  , 4.6 ],
       [1.  , 0.45, 1.  , 0.25, 1.65],
       [1.  , 1.95, 1.35, 4.15, 1.8 ],
       [1.  , 1.4 , 2.7 , 0.7 , 4.  ],
       [1.  , 0.35, 4.95, 3.85, 1.  ],
       [1.  , 0.05, 4.1 , 3.55, 3.65],
       [1.  , 3.85, 0.35, 1.8 , 0.6 ],
       [1.  , 0.86, 0.62, 0.33, 0.06],
       [1.  , 0.31, 0.33, 0.73, 0.64],
       [1.  , 0.89, 0.47, 0.12, 0.71],
       [1.  , 0.76, 0.56, 0.77, 0.49],
       [1.  , 0.52, 0.43, 0.03, 0.11],
       [1.  , 0.03, 0.64,

In [53]:
import math

def back_prop(x,r,H,K,D,step_size,accuracy_stop,iterations):
    
    v_weights = np.random.uniform(low=-0.01, high=0.01, size=(K,H+1))
    w_weights = np.random.uniform(low=-0.01, high=0.01, size=(H,D+1))
    
    for run in range(iterations):
        accuracy_score = 0
        
        delta_w = np.zeros(shape=(H,D+1))
        delta_v = np.zeros(shape=(K,H+1))
        
        for t in range(len(x)):
            
            #feed forward of hidden units
            z = np.zeros(shape=(H+1))
            z[0] = 1
            
            for h in range(1,H):
                z[h] = np.dot(np.transpose(w_weights[h]),x[t])
            
            z_bounded = np.zeros(shape=(H+1))
            z_bounded[0] = 1
            
            #we are chosing either sigmoid or softmax 
            for index in range(len(z)):
                if z[index] >=0:
                    z_bounded[index] = 1/(1+np.exp(-z[index]))
                else:
                    z_bounded[index] = np.exp(z[index])/(1+np.exp(z[index]))
                    
            o = np.zeros(shape=(K))
            y = np.zeros(shape=(K))
            
            for i in range(K):
                o[i] = np.dot(np.transpose(v_weights[i]),z_bounded)
            
            #feed forward of outputs units
            
            #this is important to prevent overflow errors
            max_o = max(o)
            o2 = [np.exp(x-max_o) for x in o]
            denom = sum(o2)
            
            for i in range(K):
                y[i] = (o2[i]/denom)
                
            if np.argmax(r[t]) == np.argmax(y):
                accuracy_score = accuracy_score + 1
                
            for i in range(K):                  
                delta_v[i] = step_size*(r[t,i]-y[i])*z_bounded
            
            for h in range(H):
                diff = 0
                for i in range(K):
                    diff += (r[t,i]-y[i])*v_weights[i,h]
                delta_w[h] = step_size*diff*z_bounded[h]*(1-z_bounded[h])*x[t]
            
            for i in range(K):
                v_weights[i] = v_weights[i] + delta_v[i]
                
            for h in range(H):
                w_weights[h] = w_weights[h] + delta_w[h]
        
        if (accuracy_score/len(x) >= accuracy_stop):
            print("Training Accuracy: " + str(accuracy_score/len(x)*100))
            return ({"v_weights": v_weights, "w_weights": w_weights})
        
    print("Training Accuracy: " + str(accuracy_score/len(x)*100))
    return ({"v_weights": v_weights, "w_weights": w_weights})

In [54]:
back_prop(X,R,H,K,D,0.5,.5,5)

Training Accuracy: 83.33333333333334


{'v_weights': array([[-0.5058787 , -0.23254656, -0.20910362, -0.2022117 , -0.2293512 ,
         -0.19209655, -0.21466653, -0.20657294, -0.21837953, -0.20382189,
         -0.33994287],
        [-0.05686433, -0.21110927, -0.21275778, -0.21589805, -0.20764571,
         -0.22550595, -0.20625481, -0.20305512, -0.21708459, -0.2169764 ,
         -0.04229927],
        [ 0.56427461,  0.42295872,  0.426046  ,  0.43033302,  0.44008161,
          0.42434076,  0.42711588,  0.42874161,  0.43381503,  0.42597445,
          0.37150182]]),
 'w_weights': array([[-0.0496255 ,  0.11523964,  0.007239  ,  0.21390571, -0.03167133],
        [-0.01903163,  0.06001707, -0.05304038,  0.13532755, -0.09751213],
        [-0.02636564,  0.06097586, -0.05925965,  0.13224542, -0.12141195],
        [-0.01523278,  0.05449273, -0.05190508,  0.12001766, -0.13283324],
        [-0.01188118,  0.06332654, -0.04035404,  0.13673236, -0.10792543],
        [-0.00987989,  0.03768356, -0.06483333,  0.10568094, -0.14145584],
        [